CREATE DATABASE QLYNHAHANGDACHINHANH
GO
USE QLYNHAHANGDACHINHANH
GO
CREATE TABLE KHACHHANG (
    MAKH         INT IDENTITY PRIMARY KEY,
    TENKH        NVARCHAR(100) NOT NULL,
    SODIENTHOAI  VARCHAR(20) NOT NULL,
    EMAIL        VARCHAR(100) NOT NULL,
    DIEMTICHLUY  INT DEFAULT 0
)
CREATE TABLE NHACUNGCAP (
    MANCC  INT IDENTITY PRIMARY KEY,
    TENNCC NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(200),
    SODIENTHOAI VARCHAR(20),
    EMAIL  VARCHAR(100)
)
CREATE TABLE CALAMVIEC (
    MACA        NVARCHAR(11)  PRIMARY KEY,
    TENCA       NVARCHAR(50)  NOT NULL,
    GIOBATDAU   TIME          NOT NULL,
    GIOKETTHUC  TIME          NOT NULL
)
CREATE TABLE CHUCVU (
    MACHUCVU   NVARCHAR(11)  PRIMARY KEY,
    TENCHUCVU  NVARCHAR(100) NOT NULL
)


CREATE TABLE LOAIKHUYENMAI (
    MALOAI NVARCHAR(10) PRIMARY KEY,
    TENLOAI NVARCHAR(50)
)
CREATE TABLE KHUYENMAI (
    MAKM        INT IDENTITY PRIMARY KEY,
    TENKM       NVARCHAR(100) NOT NULL,
    GIATRI      MONEY CHECK (GIATRI >= 0),
    DIEUKIEN    NVARCHAR(200),
    NGAYBATDAU  DATE,
    NGAYKETTHUC DATE,
    TRANGTHAI   BIT,
    MALOAI      NVARCHAR(10),
    CONSTRAINT FK_KHUYENMAI_MALOAI FOREIGN KEY (MALOAI)
        REFERENCES LOAIKHUYENMAI(MALOAI),
    CONSTRAINT CK_KHUYENMAI_NGAY CHECK (NGAYKETTHUC >= NGAYBATDAU)
)
CREATE TABLE VOUCHER (
    MAVOUCHER      NVARCHAR(20) PRIMARY KEY,
    MAKM           INT NOT NULL, 
    MAKHACHHANG    INT,          
    NGAYPHATSINH   DATE DEFAULT GETDATE(),
    NGAYHETHAN     DATE,
    TRANGTHAI      BIT DEFAULT 1, 
    DADUOCSUDUNG   BIT DEFAULT 0,
    CONSTRAINT FK_VOUCHER_KM FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM),
    CONSTRAINT FK_VOUCHER_KH FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKH)
)
CREATE TABLE CHINHANH (
    MACHINHANH   NVARCHAR(11)  PRIMARY KEY,
    TENCHINHANH  NVARCHAR(100) NOT NULL,
    DIACHI       NVARCHAR(200) NOT NULL,
    SODIENTHOAI  VARCHAR(20),
    MACHUCVUQL   NVARCHAR(11)NOT NULL,--Quản lý chi nhánh
    TRANGTHAI    BIT           NOT NULL,
    CONSTRAINT FK_CHINHANH_CHUCVU
    FOREIGN KEY (MACHUCVUQL) REFERENCES CHUCVU(MACHUCVU)
)
CREATE TABLE LOAINHANVIEN (
    MALOAI NVARCHAR(10) PRIMARY KEY,
    TENLOAI NVARCHAR(50) NOT NULL
)
CREATE TABLE NHANVIEN (
    MANHANVIEN  INT IDENTITY PRIMARY KEY,
	    MALOAI NVARCHAR(10) NOT NULL,
    HOTEN       NVARCHAR(100) NOT NULL,
    NGAYSINH    DATE,
    CCCD        VARCHAR(20) NOT NULL,
    SODIENTHOAI VARCHAR(20) NOT NULL,
    DIACHI      NVARCHAR(200) NOT NULL,
    MACHINHANH  NVARCHAR(11)  NOT NULL,
    NGAYVAOLAM  DATE          NOT NULL,
    TRANGTHAI   NVARCHAR(50)  NOT NULL,
    CONSTRAINT FK_NHANVIEN_CHINHANH FOREIGN KEY (MACHINHANH) REFERENCES CHINHANH(MACHINHANH),
CONSTRAINT FK_NHANVIEN_LOAINV FOREIGN KEY (MALOAI) REFERENCES LOAINHANVIEN(MALOAI)
)
ALTER TABLE NHANVIEN ADD MACHUCVU NVARCHAR(11)
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_CHUCVU
FOREIGN KEY (MACHUCVU) REFERENCES CHUCVU(MACHUCVU)
CREATE TABLE KHU (
    MAKHU      NVARCHAR(50) PRIMARY KEY,
    TENKHU     NVARCHAR(50) NOT NULL,
	MACHINHANH   NVARCHAR(11),
	CONSTRAINT FK_KHU_CHINHANH 
	FOREIGN KEY (MACHINHANH) REFERENCES CHINHANH(MACHINHANH) 
)
CREATE TABLE BANAN (
    MABAN        INT IDENTITY PRIMARY KEY,
    TENBAN       NVARCHAR(50) NOT NULL,
    MACHINHANH   NVARCHAR(11) NOT NULL,
    TRANGTHAI    NVARCHAR(50) NOT NULL,
    MAKHU        NVARCHAR(50),
    CONSTRAINT FK_BAN_BRANCH FOREIGN KEY (MACHINHANH) REFERENCES CHINHANH(MACHINHANH),
CONSTRAINT FK_BAN_KHU FOREIGN KEY (MAKHU) REFERENCES KHU(MAKHU)
)
CREATE TABLE NGUOIDUNG (
    MANGUOIDUNG NVARCHAR(11)  PRIMARY KEY,
    TENNGUOIDUNG VARCHAR(50)  NOT NULL UNIQUE,
    MATKHAU      VARCHAR(500) NOT NULL,            
    HOVATEN      NVARCHAR(100),
    EMAIL        VARCHAR(100),
    SODIENTHOAI  VARCHAR(20),
    MACHINHANH   NVARCHAR(11),
    MACHUCVU     NVARCHAR(11),
    TRANGTHAI    BIT NOT NULL,
CONSTRAINT FK_USER_BRANCH FOREIGN KEY (MACHINHANH) REFERENCES CHINHANH(MACHINHANH),
CONSTRAINT FK_USER_ROLE   FOREIGN KEY (MACHUCVU)  REFERENCES CHUCVU(MACHUCVU)
)
CREATE TABLE CHUCNANG (
    MACHUCNANG  NVARCHAR(11)  PRIMARY KEY,
    TENCHUCNANG NVARCHAR(50)  NOT NULL
)
CREATE TABLE PHANQUYEN (
    MANGUOIDUNG NVARCHAR(11) NOT NULL,
    MACHUCNANG  NVARCHAR(11) NOT NULL,
    CONSTRAINT PK_PHANQUYEN      PRIMARY KEY (MANGUOIDUNG, MACHUCNANG),
    CONSTRAINT FK_PQ_USER FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG),
    CONSTRAINT FK_PQ_CHUCNANG    FOREIGN KEY (MACHUCNANG)  REFERENCES CHUCNANG(MACHUCNANG)
)
CREATE TABLE CHAMCONG (
    MACHAMCONG INT IDENTITY PRIMARY KEY,
    MANHANVIEN INT NOT NULL,
    MACA       NVARCHAR(11) NOT NULL,
    NGAY       DATE NOT NULL,
    GIOVAO     TIME,
    GIORA      TIME,
    TRANGTHAI  NVARCHAR(50),
    CONSTRAINT FK_CC_NHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
    CONSTRAINT FK_CC_CALA FOREIGN KEY (MACA) REFERENCES CALAMVIEC(MACA),
    CONSTRAINT UQ_CC_UNIQUE UNIQUE (MANHANVIEN, MACA, NGAY)  
)
CREATE TABLE LUONG_FULLTIME (
    MALUONG     INT IDENTITY PRIMARY KEY,
    MANHANVIEN  INT NOT NULL,
    THANG       INT NOT NULL CHECK (THANG BETWEEN 1 AND 12),
    NAM         INT NOT NULL,
    LUONGCOBAN  MONEY NOT NULL,
    PHUCAP      MONEY DEFAULT 0,
    THUONG      MONEY DEFAULT 0,
    KHAUTRU     MONEY DEFAULT 0,
    TONGLUONG   AS (LUONGCOBAN + PHUCAP + THUONG - KHAUTRU) PERSISTED,
    CONSTRAINT FK_LUONGFT_NV FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)
CREATE TABLE LUONG_PARTTIME (
    MALUONG     INT IDENTITY PRIMARY KEY,
    MANHANVIEN  INT NOT NULL,
    THANG       INT NOT NULL CHECK (THANG BETWEEN 1 AND 12),
    NAM         INT NOT NULL,
    SOGIOCONG   INT NOT NULL,
    LUONGTHEOGIO MONEY NOT NULL,
    THUONG      MONEY DEFAULT 0,
    KHAUTRU     MONEY DEFAULT 0,
    TONGLUONG   AS (SOGIOCONG * LUONGTHEOGIO + THUONG - KHAUTRU) PERSISTED,
    CONSTRAINT FK_LUONGPT_NV FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)
CREATE TABLE NGUYENLIEU (
    MANGUYENLIEU INT IDENTITY PRIMARY KEY,
    TENNGUYENLIEU NVARCHAR(200) NOT NULL,
    DONVITINH     NVARCHAR(50)  NOT NULL,
    SOLUONG       FLOAT         NOT NULL CHECK (SOLUONG >= 0),
    HANSUDUNG     DATE,
    MACHINHANH    NVARCHAR(11)  NOT NULL,
    TRANGTHAI     BIT DEFAULT 1,  
    CONSTRAINT FK_NL_BRANCH FOREIGN KEY (MACHINHANH) REFERENCES CHINHANH(MACHINHANH)
)
CREATE TABLE DANHMUCMON (
    MADANHMUC   NVARCHAR(11)  PRIMARY KEY,
    TENDANHMUC  NVARCHAR(100) NOT NULL
)
CREATE TABLE MONAN (
    MAMON     INT IDENTITY PRIMARY KEY,
    TENMON    NVARCHAR(100) NOT NULL,
    GIA       MONEY         NOT NULL,
    HINHANH   NVARCHAR(500),
    GHICHU    NVARCHAR(200),
    MADANHMUC NVARCHAR(11)  NOT NULL,
    CONSTRAINT FK_MON_DANHMUC FOREIGN KEY (MADANHMUC) REFERENCES DANHMUCMON(MADANHMUC)
)
CREATE TABLE DINHMUC (
    MAMON         INT NOT NULL,
    MANGUYENLIEU  INT NOT NULL,
    SOLUONG       FLOAT NOT NULL CHECK (SOLUONG > 0),
    CONSTRAINT PK_DINHMUC PRIMARY KEY (MAMON, MANGUYENLIEU),
    CONSTRAINT FK_DM_MONAN FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON),
    CONSTRAINT FK_DM_NGUYENLIEU FOREIGN KEY (MANGUYENLIEU) REFERENCES NGUYENLIEU(MANGUYENLIEU)
)
CREATE TABLE PHIEUNHAP (
    MAPHIEUNHAP INT IDENTITY PRIMARY KEY,
    NGAYNHAP    DATE NOT NULL,
    MANCC       INT  NOT NULL,
    MANHANVIEN  INT  NOT NULL,
    TONGTIEN    MONEY,
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC)      REFERENCES NHACUNGCAP(MANCC),
CONSTRAINT FK_PN_NV  FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)
CREATE TABLE CHITIETPHIEUNHAP (
    MAPHIEUNHAP   INT   NOT NULL,
    MANGUYENLIEU  INT   NOT NULL,
    SOLUONG       FLOAT NOT NULL,
    DONGIA        MONEY NOT NULL,
    THANHTIEN     AS (SOLUONG * DONGIA) PERSISTED, -- Tính tự động
    CONSTRAINT PK_CTPN PRIMARY KEY (MAPHIEUNHAP, MANGUYENLIEU),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAP(MAPHIEUNHAP),
    CONSTRAINT FK_CTPN_NL FOREIGN KEY (MANGUYENLIEU) REFERENCES NGUYENLIEU(MANGUYENLIEU)
)
CREATE TABLE HINHTHUCTHANHTOAN (
    MAHTTT         INT IDENTITY PRIMARY KEY,
    TENHTTT        NVARCHAR(100) NOT NULL,
)
CREATE TABLE HOADON (
    MAHD        INT IDENTITY PRIMARY KEY,
    NGAYLAP     DATETIME     NOT NULL DEFAULT GETDATE(),
    MANV        INT          NOT NULL,
    MABAN       INT          NOT NULL,
    TONGTIENHANG MONEY, -- Tổng tiền món ăn chưa thuế
    VAT         FLOAT DEFAULT 0, -- Thuế suất (%)
    TIENVAT     AS (TONGTIENHANG * VAT / 100) PERSISTED,
    TONGTIEN    AS (TONGTIENHANG + (TONGTIENHANG * VAT / 100)) PERSISTED,
    HINHTHUCTHANHTOAN  NVARCHAR(50),
    TRANGTHAI   NVARCHAR(50),
    CONSTRAINT FK_HD_NV  FOREIGN KEY (MANV)  REFERENCES NHANVIEN(MANHANVIEN),
    CONSTRAINT FK_HD_BAN FOREIGN KEY (MABAN) REFERENCES BANAN(MABAN)
)
CREATE TABLE CHITIETHOADON (
    MAHD     INT NOT NULL,
    MAMON    INT NOT NULL,
    SOLUONG  INT NOT NULL,
    DONGIA   MONEY NOT NULL,
    CONSTRAINT PK_CTHD          PRIMARY KEY (MAHD, MAMON),
    CONSTRAINT FK_CTHD_HD       FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
CONSTRAINT FK_CTHD_MON      FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON)
)
CREATE TABLE DATBAN (
    MADAT     INT IDENTITY PRIMARY KEY,
    MAKH      INT NOT NULL,
    MABAN     INT NOT NULL,
    NGAYDAT   DATETIME NOT NULL,
    GIODAT    TIME NOT NULL,              -- Tách giờ đặt riêng để xử lý linh hoạt
    GHICHU    NVARCHAR(200),
    TRANGTHAI NVARCHAR(50) DEFAULT N'Chờ xác nhận',
    CONSTRAINT FK_DB_KH   FOREIGN KEY (MAKH)  REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_DB_BAN  FOREIGN KEY (MABAN) REFERENCES BANAN(MABAN)
)
CREATE TABLE DANHGIA (
    MADANHGIA   INT IDENTITY PRIMARY KEY,
    MAKH        INT NOT NULL,
    MAMON       INT NOT NULL,
    DIEM        INT CHECK (DIEM BETWEEN 1 AND 5),
    NOIDUNG     NVARCHAR(200),
    NGAYDANHGIA DATE default GETDATE(),
    CONSTRAINT FK_DG_KH  FOREIGN KEY (MAKH)  REFERENCES KHACHHANG(MAKH),
CONSTRAINT FK_DG_MON FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON)
)
CREATE TABLE LSU_DANGNHAP (
    MALSDN       INT IDENTITY PRIMARY KEY,
    MANGUOIDUNG  NVARCHAR(11) NOT NULL,
    THOIGIANVAO  DATETIME     NOT NULL DEFAULT GETDATE(),
    THOIGIANRA   DATETIME,
    DIA_CHI_IP   VARCHAR(50),         
    THIETBI      NVARCHAR(100),       
    CONSTRAINT FK_LSDN_USER FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG)
)
CREATE TABLE NHATKY (
    MANHATKY     INT IDENTITY PRIMARY KEY,
    TENDANGNHAP  VARCHAR(50) NOT NULL,
    MACHUCNANG   NVARCHAR(11) NOT NULL,
    HANHDONG     NVARCHAR(200),       
    THOIGIAN     DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_NK_FUNC FOREIGN KEY (MACHUCNANG) REFERENCES CHUCNANG(MACHUCNANG)
)
-- Bảng KHACHHANG
INSERT INTO KHACHHANG (TENKH, SODIENTHOAI, EMAIL, DIEMTICHLUY) VALUES
(N'Nguyễn Văn Anh', '0909123456', 'nguyenvananh@gmail.com', 120),
(N'Trần Thị Bầu', '0987654321', 'tranthibau@yahoo.com', 80),
(N'Phạm Văn Chung', '0912345678', 'phamvanchung@hotmail.com', 50),
(N'Hoàng Thị Dương', '0933445566', 'hoangthiduong@gmail.com', 150),
(N'Vũ Văn Em', '0966123456', 'vuvanem@gmail.com', 30),
(N'Lê Thị Hằng', '0922334455', 'lethihang@gmail.com', 200),
(N'Đặng Văn Giang', '0911223344', 'dangvangiang@gmail.com', 90),
(N'Bùi Thị Hoa', '0977555333', 'buithihoa@yahoo.com', 60);

-- Bảng NHACUNGCAP
INSERT INTO NHACUNGCAP (TENNCC, DIACHI, SODIENTHOAI, EMAIL) VALUES
(N'Công ty TNHH Thực phẩm ABC', N'123 Đường Lê Lợi, Hà Nội', '0249123456', 'abc@thucpham.vn'),
(N'Công ty TNHH Thủy sản XYZ', N'456 Đường Trần Hưng Đạo, Đà Nẵng', '0236389123', 'xyz@thuysan.vn'),
(N'Công ty TNHH Nông sản Sạch', N'789 Đường Phan Đình Phùng, TP.HCM', '0283891234', 'nongsach@gmail.com'),
(N'Công ty TNHH Gia vị Việt', N'111 Đường Nguyễn Trãi, Hà Nội', '0243921234', 'givi@vietspice.vn'),
(N'Công ty TNHH Thức ăn chăn nuôi Minh Phát', N'222 Đường Lý Thường Kiệt, Cần Thơ', '0292389123', 'minhphat@feed.vn'),
(N'Công ty TNHH Bao bì Long An', N'333 Đường Nguyễn Huệ, Long An', '0272389123', 'baobi@longan.vn'),
(N'Công ty TNHH Đóng gói Đại Nam', N'444 Đường Hùng Vương, Hải Phòng', '0225389123', 'daian@pack.vn'),
(N'Công ty TNHH Vật tư Nông nghiệp Xanh', N'555 Đường Võ Văn Kiệt, Bình Dương', '0274389123', 'xanh@vattu.vn');


-- Bảng LOAINHANVIEN
INSERT INTO LOAINHANVIEN (MALOAI, TENLOAI) VALUES
('LNV01', N'Nhân viên chính thức'),
('LNV02', N'Nhân viên thử việc'),
('LNV03', N'Nhân viên part-time'),
('LNV04', N'Quản lý'),
('LNV05', N'Nhân viên giao nhận'),
('LNV06', N'Nhân viên kho'),
('LNV07', N'Nhân viên tạp vụ'),
('LNV08', N'Nhân viên bảo vệ');
-- Bảng CALAMVIEC
INSERT INTO CALAMVIEC (MACA, TENCA, GIOBATDAU, GIOKETTHUC) VALUES
('CA001', N'Ca sáng', '07:00', '15:00'),
('CA002', N'Ca chiều', '15:00', '23:00'),
('CA003', N'Ca đêm', '23:00', '07:00'),
('CA004', N'Ca phụ', '10:00', '18:00'),
('CA005', N'Ca hành chính', '08:00', '17:00'),
('CA006', N'Ca linh hoạt', '12:00', '20:00'),
('CA007', N'Ca cuối tuần', '09:00', '17:00'),
('CA008', N'Ca lễ', '08:00', '16:00');

-- Bảng CHINHANH
INSERT INTO CHINHANH (MACHINHANH, TENCHINHANH, DIACHI, SODIENTHOAI, MACHUCVUQL, TRANGTHAI) VALUES
('CN001', N'Chi nhánh Hà Nội', N'123 Đường Lê Duẩn, Hà Nội', '02439321234', 'CV001', 1),
('CN002', N'Chi nhánh Đà Nẵng', N'456 Đường Nguyễn Văn Linh, Đà Nẵng', '02363891234', 'CV001', 1),
('CN003', N'Chi nhánh TP.HCM', N'789 Đường Nguyễn Thị Minh Khai, TP.HCM', '02838912345', 'CV001', 1),
('CN004', N'Chi nhánh Cần Thơ', N'101 Đường Trần Hưng Đạo, Cần Thơ', '02923891234', 'CV001', 1),
('CN005', N'Chi nhánh Hải Phòng', N'202 Đường Lạch Tray, Hải Phòng', '02253891234', 'CV001', 1),
('CN006', N'Chi nhánh Bình Dương', N'303 Đường Phú Lợi, Bình Dương', '02743891234', 'CV001', 1),
('CN007', N'Chi nhánh Long An', N'404 Đường Nguyễn Huệ, Long An', '02723891234', 'CV001', 1),
('CN008', N'Chi nhánh Quảng Ninh', N'505 Đường Hạ Long, Quảng Ninh', '02033891234', 'CV001', 1);

-- Bảng CHUCVU
INSERT INTO CHUCVU (MACHUCVU, TENCHUCVU) VALUES
('CV001', N'Quản lý chi nhánh'),
('CV002', N'Nhân viên phục vụ'),
('CV003', N'Đầu bếp'),
('CV004', N'Thu ngân'),
('CV005', N'Nhân viên giao hàng'),
('CV006', N'Bảo vệ'),
('CV007', N'Kế toán'),
('CV008', N'Quản lý kho');
